spring:
  profiles:
    active: production
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
    open-in-view: false
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  redis:
    host: localhost
    port: 6379
logging:
  level:
    root: INFO